name: Rust-builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libudev dependencies
      run: sudo apt-get update && sudo apt-get install -y libudev-dev libx11-dev pkg-config
    - name: Build
      run: cargo build --verbose
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
